moamoa/.eslintrc.js, moamoa/src/Pages/ProductDetail.jsx, moamoa/src/Pages/ProductList.jsx, moamoa/src/index.js
다음 구현 계획은 
축제와 체험 분리와 상세리스트로 이동입니다.
Issue Number
=> [✨ Feature] 상품리스트 구현 중입니다.

moamoa/src/App.js, moamoa/src/Pages/AddProduct.jsx
+ AddProduct 파일을 이전 기능 구현했던 파일로 코드 수정했습니다.
+ App.js 파일에서 esLint 에러 'GlobalStyle' is not defined 가 출력되어서 주석 처리 해제했습니다.
Issue Number
close: # 40
=> [🔧 Fix] App.js 파일과 AddProduct 파일 오류 수정

moamoa/src/Router/AppRoutes.js
AppRoutes.js 파일의 ESLint 오류 수정했습니다.
Issue Number
close: # 50
=> [🔧 Fix] AppRoutes.js 파일의 ESLint 오류 수정

moamoa/src/Pages/Post/UploadPost.jsx
+ AppRoutes.js : 게시글 작성 페이지 경로 추가
+ ProfileInfo.jsx : accountname을 임시로 지정
+ AddPost.jsx : 게시글 작성 페이지(메인 주제)
+ 이미지 첨부 구현
+ 이미지 닫기 버튼 구현
+ 게시글 등록 버튼 클릭 시 첨부한 이미지와 작성한 내용을 서버에 저장
+ 게시글을 작성하는 사용자의 프로필 이미지 출력
Issue Number
close: # 52
=> [✨ Feature] 게시글 작성 페이지 마크업 및 구현

moamoa/src/Pages/Home/Home.jsx
내가 팔로우 하는 사람의 게시글이 있는 경우와 없는 경우로 나눠서 렌더링 되도록 구현했습니다.
heart count 부분의 숫자 카운팅이 빠져서.. 추가하도록 하겠습니다.
게시글 상세 페이지를 구현하고, 홈 화면에서 게시글로 이동할 수 있도록 라우터 설정할 예정입니다!
Issue Number #33 
=> [✨ Feature] Home 페이지 구현

moamoa/src/Pages/Login/Login.jsx
+ 이메일과 비밀번호 모두 입력 시 버튼 활성화
+ 로그인 버튼 클릭 시 유효성 검사 진행 - 이메일 주소 또는 비밀번호 불일치 시 경고 문구 출력
+ 입력창에 focus 시 선의 색 변화
+ 로그인 성공 시 홈으로 페이지 이동
+ 로그인 성공 시 받는 토큰을 useSetRecoilState을 사용하여 로컬 스토리지에 저장 
로그인 페이지 추가 계획
: 로그인 버튼 클릭 시 유효성 검사 진행 - 이메일 주소 형식 
Issue Number
close: # 55
=> [✨ Feature] 이메일로 로그인 페이지 기능 추가

moamoa/.eslintrc.js, moamoa/src/Pages/Login/Login.jsx, moamoa/src/Router/AppRoutes.js
=> [🔧 Fix] 깃 전략을 바꾸기 위한 푸시입니다.

moamoa/src/Pages/Home/Home.jsx, moamoa/src/Pages/Join/Join.jsx, moamoa/src/Pages/Login/Login.jsx, moamoa/src/Pages/Post/PostDetail.jsx, moamoa/src/Pages/Post/UploadPost.jsx, moamoa/src/Pages/Product/AddProduct.jsx, moamoa/src/Pages/Product/ProductList.jsx, moamoa/src/Pages/Profile/EditProfile.jsx, moamoa/src/Pages/Profile/YourProfile.jsx
Recoil 폴더 안 파일명이 바뀌면서 컴파일 에러가 뜨고 있습니다.
따라서 eventTypeAtom, followPostAtom, userTokenAtom, userTypeAtom을 import해서 사용한 각 파일들의 경로를 수정하는 작업을 했습니다.   
<b>충돌이 생기지 않도록 아래 페이지의 줄에서 수정이 필요하시다면 다음 merge하실 때 수정해주시면 감사하겠습니다! </b>  
Home.jsx - 2번째, 5번째 줄
Join.jsx - 5번째 줄
Login.jsx - 5번째 줄
PostDetail.jsx - 4번째 줄, 5번째 줄
UploadPost.jsx - 3번째 줄
AddProduct.jsx - 4번째 줄, 7번째 줄
ProductList.jsx - 6번째 줄
EditProfile.jsx - 10번째 줄
YourProfile.jsx - 12번째 줄, 14번째 줄
=> 혹시 몰라 제가 수정한 파일의 줄을 적어두겠습니다. 감사합니다.
Issue Number
close: # 68
=> [🔧 Fix] Recoil 파일명 변경으로 인한 컴파일 에러 수정

moamoa/.eslintrc.js, moamoa/package-lock.json, moamoa/package.json, moamoa/src/Components/Common/Header.jsx, moamoa/src/Components/Common/ProductImgBox.jsx, moamoa/src/Pages/Product/ProductList.jsx
ProductImgBox.jsx
상품 리스트 이미지 스타일 컴포넌트를 구현했습니다
파일을 분리하니 렌더링이 안되어 prop-Types를 이용했습니다
npm install prop-types 설치 필요합니다 ProductImgBox 파일에 주석 넣었습니다
ProductImgBox.jsx
상품 리스트 이미지 스타일 컴포넌트를 구현했습니다
파일을 분리하니 렌더링이 안되어 prop-Types를 이용했습니다
npm install prop-types 설치 필요합니다 ProductImgBox 파일에 주석 넣었습니다
Issue Number
=> [🌈 Style] 상품 리스트 이미지 스타일 컴포넌트 구현했습니다.

moamoa/src/Pages/Product/AddProduct.jsx
+ 컴포넌트가 업데이트될 때는 사용자의 입력값이 api 요청으로 보낼 데이터에 잘 들어갔는데
컴포넌트가 마운트되었을 때 초기 설정한 상태값 1이 들어가는 상황 발생, useEffect를 사용하여 해결하였습니다.
+ 필수 기능
+ [x] 행사 이미지, 행사유형(축제/체험), 행사명, 행사기간, 행사 상세 설명을 입력받을 수 있으며, 모든 입력이 완료되면 저장 버튼이 활성화됩니다.   
+ [x] 행사명은 2~22자 이내로 입력되게 합니다.    
+ 추가 기능
+ [x] 행사 유형은 useSetRecoilState를 사용하여 로컬 스토리지에 저장되도록 합니다.   
+ [x] 행사 기간은 사용자가 선택한 행사 시작 날짜와 행사 종료 날짜를 '-'를 뺀 문자열로 처리 후 두 값을 합치고 숫자로 변환하여 'price'에 담아 api 요청을 보냅니다. (ex. 2023103020231128)
+ [x] 행사 시작 날짜가 행사 종료 날짜보다 늦은 날짜로 선택된다면 안내 메세지를 출력합니다.   
```
참고> 상품 등록 API Req
{
"product":{
"itemName": String,
"price": Number,//1원 이상
"link": String,
"itemImage": String
}
}
```
+ 다음 계획
+ 상품 수정 페이지를 구현합니다.
+ 상품 등록 페이지와 공통되는 컴포넌트를 뽑아냅니다.
+ 상품 수정 페이지와 상품 등록 페이지의 스타일 작업.
Issue Number
close: # 70
=> [✨ Feature] 상품 등록 페이지 기능 수정

moamoa/src/Components/Common/FollowButton.jsx, moamoa/src/Components/Common/ProfileDetail.jsx, moamoa/src/Pages/Profile/MyProfile.jsx, moamoa/src/Pages/Profile/YourProfile.jsx
- 페이지 분리 : 내프로필/남의 프로필
- 컴포넌트화 : 팔로우/언팔로우 버튼 기능, 프로필 디테일 페이지 상단 공통 마크업
계획
- 프로필 디테일 페이지 상단부분 style component 적용
- 프로필 디테일 페이지 내 게시글 컴포넌트화
- 팔로우/언팔로우 버튼 style component 적용
Issue Number #79
=> ✨Feat: 남의프로필/내프로필 분리, 팔로우/언팔로우 버튼 기능 컴포넌트화, 프로필 디테일 페이지 공통 마크업 컴포넌트화

moamoa/src/API/Auth/JoinAPI.jsx, moamoa/src/API/Auth/LoginAPI.jsx, moamoa/src/API/Img/UploadImageAPI.jsx, moamoa/src/API/Product/ProductDetailAPI.jsx, moamoa/src/API/Product/ProductEditAPI.jsx, moamoa/src/API/Product/ProductUploadAPI.jsx, moamoa/src/API/Valid/AccountValidAPI.jsx, moamoa/src/API/Valid/EmailValidAPI.jsx
+ 코드 구조화와 유지보수성, 재사용성 향상을 위해 API 모듈 분리화 작업을 했습니다.
+ 모듈 분리한 폴더 구조 사진은 아래 첨부하겠습니다.
+ 다음 계획   
+ 회원가입과 로그인 페이지 & 기능 구현 PR 보낼 예정입니다.
Issue Number
close: # 78
=> [♻️ Refactor] API 모듈 분리화 작업

moamoa/src/Hooks/Sign/useJoin.jsx, moamoa/src/Hooks/Sign/useLogin.jsx, moamoa/src/Pages/Join/Join.jsx, moamoa/src/Pages/Login/Login.jsx, moamoa/src/Pages/Profile/SetProfile.jsx, moamoa/src/Recoil/accountNameAtom.jsx, moamoa/src/Recoil/isLoginAtom.jsx
+ 이메일로 로그인, 회원 가입, 프로필 설정 필수 기능 & 컴포넌트 리팩토링 마쳤습니다. 
- 이메일로 로그인
- 회원가입
- 프로필 설정
Issue Number
close: # 86
=> [♻️ Refactor] 회원가입(프로필 포함)과 이메일로 로그인 페이지 필수 기능 & 컴포넌트 리팩토링

moamoa/src/Pages/Post/UploadPost.jsx, moamoa/src/Pages/Profile/EditProfile.jsx
[프로필 수정 페이지]
- 유효성 검사를 통과하지 못한 경우 경고 문구가 각 입력창 하단에 표시
- 유효성 검사가 통과되지 않을 경우 `수정하기` 버튼 비활성화
- 작성이 완료된 후, 유효성 검사를 통과할 경우 `수정하기` 버튼이 활성화
[게시글 작성 페이지]
- 글이 입력되거나 사진이 업로드 되면 `업로드` 버튼이 활성화
| 프로필 수정 페이지1 | 프로필 수정 페이지2 | 게시글 작성 페이지 |
|---|---|---|
| ![프로필 수정1](https://github.com/FRONTENDSCHOOL7/final-18-moamoa/assets/116999139/50436a54-51f9-49b7-9c16-afdb884317d4) | ![프로필 수정2](https://github.com/FRONTENDSCHOOL7/final-18-moamoa/assets/116999139/641904c6-aaee-42da-aa5f-e7b593b33ad6) | ![게시글 작성](https://github.com/FRONTENDSCHOOL7/final-18-moamoa/assets/116999139/7c868bc2-554a-4a32-ae86-a28b8c027b36) |
계획
- 입력창에 focus 될 경우에는 선의 색이 변함(프로필 수정 페이지)
- 디자인 작업
Issue Number #106 #102 
=> [✨ Feature] 프로필 수정 페이지, 게시글 등록 페이지 기능 추가

moamoa/src/Pages/Post/EditPost.jsx, moamoa/src/Pages/Post/UploadPost.jsx
- UploadPost.jsx : handleFormSubmit기능 추가
- EditPost.jsx : 게시글 수정 페이지 기능 구현
- 기존 게시글 정보를 표시
- 글이 입력되거나 사진이 업로드 되면 `수정하기` 버튼이 활성화
- `수정하기`버튼을 누르면 수정사항이 반영된 상태로 프로필 상세 페이지로 이동
- 사진은 우측 하단 버튼을 클릭하면 업로드
계획
- postId를 props로 받아온 뒤 제대로 실행되는지 확인
Issue Number #60
=> [✨ Feature] 게시글 수정 페이지 기능 구현, 게시글 등록 페이지 기능 추가

moamoa/src/API/Follow/FollowerAPI.jsx, moamoa/src/API/Follow/FollowingAPI.jsx, moamoa/src/Components/Common/FollowUser.jsx, moamoa/src/Components/Common/FollowingUser.jsx, moamoa/src/Components/Common/GoBackbtn.jsx, moamoa/src/Pages/Follow/FollowerList.jsx, moamoa/src/Pages/Follow/FollowingList.jsx, moamoa/src/Pages/Post/PostDetail.jsx, moamoa/src/Pages/Splash/Landing.jsx
feature: follower,following 페이지 api로 팔로우,팔로잉 렌더링 했습니다.
스타일 컴포넌트 오류가 콘솔창에 있습니다.
기능은 동작하여 오류 해결을 다른 페이지 구현 후 해결하겠습니다.
버튼 컴포넌트를 불러와 props를 이용한 곳에서 오류가 발생한 것 같습니다. 기능은 동작하여 오류 해결을 다른 페이지 구현 후 해결하겠습니다.
Issue Number #115
=> [✨ Feature]: api 연결하여 팔로우,팔로잉 구현했습니다.

moamoa/src/API/Follow/FollowerAPI.jsx, moamoa/src/API/Follow/FollowingAPI.jsx, moamoa/src/Components/Common/FollowUser.jsx, moamoa/src/Components/Common/FollowingUser.jsx, moamoa/src/Components/Common/GoBackbtn.jsx, moamoa/src/Components/Common/HeaderBasic.jsx, moamoa/src/Components/Common/HeaderSearch.jsx, moamoa/src/Pages/Follow/FollowerList.jsx, moamoa/src/Pages/Follow/FollowingList.jsx, moamoa/src/Pages/Post/PostDetail.jsx, moamoa/src/Pages/Search/Search.jsx, moamoa/src/Pages/Splash/Landing.jsx, moamoa/src/Router/AppRoutes.js
피드 페이지에서 헤더의 돋보기를 클릭하면 검색 페이지로 이동합니다.
마크업만 구현하였습니다.
이동
마크업만 구현하여 기능이 있는 곳은 헤더의 뒤로가기와 푸터의 메뉴탭만 기능이 있습니다.
Issue Number #111
=> [✨Feature] Search 페이지 마크업만 구현했습니다.

moamoa/src/API/Product/ProductDetailAPI.jsx, moamoa/src/API/Product/ProductEditAPI.jsx, moamoa/src/Pages/Product/AddProduct.jsx, moamoa/src/Pages/Product/AskBtn.jsx, moamoa/src/Pages/Product/EditProduct.jsx, moamoa/src/Pages/Product/ProductDetail.jsx
+ 상품 수정 페이지 및 수정 기능 구현했습니다.
+ ProductDetailAPI reqURL 오타 수정합니다.   
+ 상품 추가 시 상품 리스트로 이동하도록 페이지 연결합니다.
--- | --- | 
Issue Number
close: # 128
=> [✨ Feature] 상품 수정 페이지 및 수정 기능 구현

moamoa/src/Assets/icons/icon-email.svg, moamoa/src/Assets/icons/icon-lock.svg, moamoa/src/Components/Common/FormLoginAndJoin.jsx, moamoa/src/Hooks/Sign/useJoin.jsx, moamoa/src/Hooks/Sign/useLogin.jsx, moamoa/src/Pages/Join/Join.jsx, moamoa/src/Pages/Login/Login.jsx
--- | --- | 
버튼 크기와 전체적인 배치(ex. 간격) 부분 봐주시면 감사하겠습니다!!
Issue Number
close: # 100
=> [🌈 Style] 회원가입 및 로그인 페이지 스타일 적용

moamoa/src/Components/Modal/DeleteModal.jsx, moamoa/src/Components/Post/PostCardItem.jsx, moamoa/src/Components/Post/PostCardList.jsx, moamoa/src/Pages/Product/AskBtn.jsx, moamoa/src/Pages/Product/ProductDetail.jsx
행사명 출력 오류, 내가 등록한 상품이 아닌데도 상품 수정 및 삭제가 가능한 오류 발생
행사명 출력 부분 slice메서드 사용해 수정했습니다. 삭제 확인 모달 추가 작업 진행했습니다.
Issue Number
close: #143
=> [🔧 Fix] 상품 상세페이지 출력 오류 해결 및 삭제 모달 추가

moamoa/src/API/Post/HeartCountDownAPI.jsx, moamoa/src/API/Post/HeartCountUpAPI.jsx, moamoa/src/Components/Home/HomePostCardList.jsx, moamoa/src/Components/Post/PostCardItem.jsx, moamoa/src/Components/Post/PostCardList.jsx, moamoa/src/Pages/Post/PostDetail.jsx
게시글 좋아요 기능 추가했습니다.
hearted 값을 사용해 이미 좋아요를 누른경우 계속 하트가 채워진 상태로 유지되도록 작업했습니다.
close: #152
=> [✨ Feature] 좋아요 기능 추가

moamoa/src/Components/Comment/Comment.jsx, moamoa/src/Components/Comment/CommentDelModal.jsx, moamoa/src/Components/Home/HomePostCardList.jsx, moamoa/src/Components/Post/PostCardItem.jsx, moamoa/src/Components/Post/PostCardList.jsx, moamoa/src/GlobalStyle.jsx, moamoa/src/Pages/Home/Home.jsx, moamoa/src/Pages/Post/PostDetail.jsx
배경이 비어있던 문제 해결했습니다 : )
Issue Number
=> [ 🌈 Style ] 홈 화면 및 게시글 상세 스타일 수정

moamoa/src/Components/Post/PostCardList.jsx, moamoa/src/Pages/Post/PostDetail.jsx
변수명 할당 오류
Issue Number
close: #175
=> [🔧 Fix] 게시글 상세페이지 오류 수정

moamoa/src/Pages/Product/AddProduct.jsx, moamoa/src/Pages/Product/EditProduct.jsx
+ 회원가입 프로필 이미지 출력 문제를 해결하기 위해 UploadImageAPI 파일을 수정했었습니다.
+ 같은 API 파일을 공유하던 상품 추가 페이지에 문제가 발생하여 해결합니다.
+ 상품 추가 페이지와 상품 수정 페이지 수정합니다.
Issue Number
close: # 187
=> [🔧 Fix] 상품 추가 페이지에서 이미지가 뜨지 않는 오류

moamoa/src/Pages/Home/Home.jsx, moamoa/src/Pages/Home/HomeFeed.jsx
홈 화면 스타일 적용이 잘못 된 문제가 있었습니다.
불필요하게 적용되었던 요소를 제거했습니다.
Issue Number
close: #190
=> [🔧 Fix] Home 화면 스타일 수정

moamoa/src/API/Post/PostDeleteAPI.jsx, moamoa/src/API/Post/PostDetailAPI.jsx, moamoa/src/API/Product/ProductDeleteAPI.jsx, moamoa/src/Components/Modal/DeleteModal.jsx, moamoa/src/Components/Post/PostCardItem.jsx, moamoa/src/Pages/Post/PostDetail.jsx
API 코드를 분리하고 어떤 게시물이 삭제되는지 명시하는 주석을 추가해 코드의 가독성을 높였습니다.
Issue Number
close: #191
=> [♻️ Refactor] PostDelete API 분리 및 DeleteModal 코드 수정

moamoa/src/API/Auth/JoinAPI.jsx, moamoa/src/API/Auth/LoginAPI.jsx, moamoa/src/API/Img/UploadImageAPI.jsx, moamoa/src/API/Product/ProductDeleteAPI.jsx, moamoa/src/API/Product/ProductDetailAPI.jsx, moamoa/src/API/Product/ProductEditAPI.jsx, moamoa/src/API/Product/ProductUploadAPI.jsx, moamoa/src/API/Valid/AccountValidAPI.jsx, moamoa/src/API/Valid/EmailValidAPI.jsx, moamoa/src/Components/Common/FormLoginAndJoin.jsx, moamoa/src/Hooks/Sign/useJoin.jsx, moamoa/src/Hooks/Sign/useLogin.jsx, moamoa/src/Pages/Product/AddProduct.jsx, moamoa/src/Pages/Product/EditProduct.jsx, moamoa/src/Pages/Sign/Join.jsx, moamoa/src/Pages/Sign/Login.jsx, moamoa/src/Router/AppRoutes.js
+ 중복 코드를 줄이고 사용하지 않는 코드는 제거 또는 주석 처리했습니다.
Issue Number
close: # 204
=> [♻️ Refactor] 로그인과 회원가입 공통 CSS 정리 및 API 응답 에러 코드 수정

moamoa/src/API/Post/HeartCountDownAPI.jsx, moamoa/src/API/Post/HeartCountUpAPI.jsx, moamoa/src/API/Post/PostDetailAPI.jsx, moamoa/src/Components/Comment/CommentDelModal.jsx, moamoa/src/Components/Comment/CommentReportModal.jsx, moamoa/src/Components/Modal/DeleteModal.jsx, moamoa/src/Components/Modal/FooterModal.jsx, moamoa/src/Components/Modal/ReportModal.jsx, moamoa/src/Components/Post/PostCardItem.jsx, moamoa/src/Pages/Post/PostDetail.jsx
게시글 상세 페이지 API 분리 및 변수명, 함수명 수정 작업 진행했습니다.
분리 후 import해 간결해진 코드입니다.
Issue Number
=> [♻️ Refactor] 게시글 상세 API 분리

moamoa/src/Pages/Profile/YourProfile.jsx
상대 프로필에서 메시지 버튼을 chatList 경로에서 상대 userName으로 연결된 채팅방으로 바꾸었습니다.
navigate의 경로를 username으로 바꾸었습니다.
전
후
Issue Number #219 
=> 상대 프로필에서 메시지 버튼을 chatList 경로에서 상대 userName으로 연결된 채팅방으로 바꾸었습니다.

moamoa/src/API/Product/ProductDeleteAPI.jsx, moamoa/src/Pages/Product/AskBtn.jsx
행사 삭제 오류 해결했습니다!
Issue Number
close: #222
=> [🔧 Fix] 행사 삭제 오류 해결

moamoa/src/Pages/Post/EditPost.jsx, moamoa/src/Pages/Post/UploadPost.jsx
- 게시글 수정 페이지와 등록페이지에 나타난 콘솔 오류를 해결했습니다.
- 게시글 수정 페이지에 나타난 콘솔 에러 해결
- 게시글 등록 페이지에 나타난 콘솔 에러 해결
계획
- 리드미 작성
Issue Number #224
=> [🔧 Fix] 콘솔 에러 해결

moamoa/src/Pages/Product/ProductDetail.jsx
+ 등록이 오래된 상품 상세 페이지 불러옵니다.
Issue Number
close: # 227
=> [🔧 Fix] 등록이 오래된 상품 상세 페이지 불러오기

moamoa/src/Components/Common/ProfileDetailPost.jsx, moamoa/src/Components/Home/HomePostCardList.jsx, moamoa/src/Components/Post/PostCardItem.jsx, moamoa/src/Components/Post/PostCardList.jsx
홈 화면과 프로필 페이지의 오류 
styled-components: it looks like an unknown prop "heartcolor" is being sent through to the DOM, which will likely trigger a React console error. If you would like automatic filtering of unknown props, you can opt-into that behavior via <StyleSheetManager shouldForwardProp={...}> (connect an API like @emotion/is-prop-valid) or consider using transient props ($ prefix for automatic filtering.)
prop을 사용하는 스타일 컴포넌트에 shouldForwardProp을 붙여주었습니다.
홈 화면의 콘솔창입니다.
프로필 페이지의 콘솔창입니다.
Issue Number #229 
=> [🔧fix] 프로필 페이지와 홈 화면의 콘솔 오류를 수정하였습니다.

moamoa/src/Components/Comment/CommentDelModal.jsx, moamoa/src/Components/Comment/CommentItem.jsx, moamoa/src/Components/Comment/CommentMoreBtn.jsx, moamoa/src/Components/Comment/CommentReportModal.jsx, moamoa/src/Components/Modal/NoticeReportModal.jsx, moamoa/src/Components/Modal/ReportModal.jsx, moamoa/src/Components/Post/PostCardItem.jsx
=> [🔧 Fix] 불필요한 코드 제거 및 신고 알림 모달 추가

moamoa/src/Hooks/Sign/useLogin.jsx
+ 배포 시 테스트 계정 ID/PW 설정합니다.
+ 로그인 화면이 떴을 때 moa_festa 계정(기관)으로 테스트 가능합니다.
Issue Number
close: # 233
=> [✨ Feature] 배포 시 테스트 계정 설정

moamoa/src/Components/Comment/Comment.jsx, moamoa/src/Components/Common/ProfileDetailProduct.jsx, moamoa/src/Components/Post/PostCardItem.jsx, moamoa/src/Pages/Profile/YourProfile.jsx
행사 삭제 새로고침 수정 및 행사 모달 버튼 내용 수정했습니다
Issue Number
close: #241
=> [🔧 Fix] 행사 삭제 새로고침 수정 및 행사 모달 버튼 내용 수정

moamoa/src/Components/Common/ProfileDetailProduct.jsx
- 프로필 수정 페이지 행사 삭제 후 업데이트 이슈를 해결했습니다.
- 삭제 API를 구현 시 상품 데이터 업데이트 과정을 추가하여 문제를 해결했습니다.
계획
- 상품 삭제시 게시글 수가 바로 바뀔 수 있도록 수정
Issue Number #245
=> [🔧 Fix] 프로필 수정 페이지 행사 삭제 후 업데이트 이슈 해결

moamoa/README.md, moamoa/src/Pages/Product/AskBtn.jsx, moamoa/src/Pages/Product/EditProduct.jsx, moamoa/src/Router/AppRoutes.js
상품 수정 페이지 경로 설정 문제로 성능검사가 불가능했습니다.
라우터 경로 설정 변경, 수정하기 버튼 눌렀을때의 경로를 변경했습니다.
수정 후 성능검사 진행해 노션에 추가했습니다!
EditProduct.jsx 파일 수정하면서 기존 코드는 일단 주석처리 해뒀습니다. 확인 후 제거 부탁드리겠습니다 : )
Issue Number
close: #250
=> Fix: 상품 수정페이지 경로 수정

moamoa/src/Assets/images/fireworks.svg, moamoa/src/Components/Splash/LoginModal.jsx, moamoa/src/Components/Splash/SplashLoginBtn.jsx, moamoa/src/Components/Splash/SplashLogo.jsx, moamoa/src/Pages/Product/ProductList.jsx, moamoa/src/Pages/Profile/YourProfile.jsx, moamoa/src/Pages/Splash/Landing.jsx, moamoa/src/md.md
한 페이지에 몰아 만들었던 페이지를 가독성을 위해 분리하였습니다.
로고 , 모달 , 로그인 버튼을 분리하고 Components 폴더 속 splash 폴더를 생성하여 넣었습니다.
분리 전 
분리 후
로고 애니메이션을 폭죽이 올라오는 느낌으로 변경했는데 확인 부탁드립니다!
Issue Number #249 
=> [♻️refactor] 스플래쉬 페이지의 컴포넌트 분리 , 로고 애니메이션 변경

moamoa/src/API/InstanceAPI.jsx, moamoa/src/API/Post/PostAPI.jsx, moamoa/src/API/Post/PostDetailAPI.jsx, moamoa/src/Components/Modal/DeleteModal.jsx, moamoa/src/Hooks/Sign/useLogin.jsx, moamoa/src/Pages/Post/PostDetail.jsx
1. axios 인스턴스 추가해 반복되는 코드를 줄이려고합니다.
2. 게시물과 관련된 API 요청들을 하나의 파일로 관리하려고 합니다.
순서대로 변경하는중이며 PostAPI 통합해 작성중입니다.
Issue Number
=> [♻️ Refactor] axios 인스턴스 추가

moamoa/src/API/Profile/ProfileAPI.jsx, moamoa/src/Components/Common/ArticleUserProfile.jsx, moamoa/src/Components/Common/ProfileDetailPost.jsx, moamoa/src/Components/Home/HomePostCardList.jsx, moamoa/src/Components/Post/PostItem.jsx, moamoa/src/Components/Post/PostList.jsx, moamoa/src/Components/Post/PostMoreBtn.jsx, moamoa/src/Pages/Home/Home.jsx, moamoa/src/Pages/Post/PostDetail.jsx, moamoa/src/Pages/Product/ProductDetail.jsx
컴포넌트 이름을 직관적으로 이해할 수 있게 변경했습니다.
Issue Number
=> refactor: 컴포넌트 이름 변경

moamoa/src/Components/Post/PostList.jsx, moamoa/src/Pages/Home/Home.jsx
로그아웃 후 다른 계정으로 로그인 시 home 피드 게시글이 다시 렌더링되지 않는 문제가 있습니다.
우선 리코일을 사용해 데이터를 불러오도록 수정했습니다. 
Issue Number
=> [🔧 Fix] post 데이터 recoil 사용한 코드로 변경

moamoa/src/Components/Common/AuthFormStyle.jsx, moamoa/src/Components/Common/ProductFormStyle.jsx, moamoa/src/Components/Product/ProductForm.jsx, moamoa/src/Hooks/Product/useDateValidation.jsx, moamoa/src/Pages/Auth/Login.jsx, moamoa/src/Pages/Auth/SignUp.jsx
+ 로그인, 회원가입, 프로필 설정, 상품등록/수정 페이지
+ 위 페이지들의 label, input(placeholder 포함)의 font 크기와 button의 크기 등을 키웠습니다. letter-spacing, word-spacing을 사용하여 자간을 넓혔습니다.
+ 페이지 안 요소 간 간격을 여유있게 조정하였습니다.
+ textarea와 input(type='date')에 font가 빠져있어서 적용했습니다.
1. 로그인 페이지   
수정 전 |수정 후
--- | --- | 
2. 회원가입 페이지
수정 전 |수정 후
--- | --- | 
3. 프로필 설정 페이지
수정 전 |수정 후
--- | --- | 
4. 상품 등록/수정 페이지
수정 전 |수정 후
--- | --- | 
페이지들 전반적으로 크기를 키워봤는데 혹시 너무 크다거나 더 키웠으면 하는 부분 있으시다면 코멘트 부탁드리겠습니다:)
Issue Number
close: # 312
=> [🔧 Fix] 폰트 크기와 자간 수정

moamoa/src/Components/Product/ProductListSkeleton.jsx, moamoa/src/Components/Product/ProductOutput.jsx, moamoa/src/Pages/Product/ProductList.jsx
1줄로 바꾼 상품리스트의 스켈레톤 UI를 수정하지 않아 수정했습니다.
수정 전
수정 후
Issue Number #324 
=> [🌈 Style] 1줄로 바꾼 상품리스트의 스켈레톤 UI 수정

moamoa/src/Assets/icons/icon-img-button.svg, moamoa/src/Components/Common/FollowUser.jsx, moamoa/src/Components/Common/FollowingUser.jsx, moamoa/src/Components/Common/SearchBtn.jsx, moamoa/src/Components/Common/SearchHighLight.jsx, moamoa/src/Components/Product/ProductOutput.jsx, moamoa/src/Components/Product/ProductStyle.js, moamoa/src/Components/Search/SearchStyle.js, moamoa/src/Components/Splash/SplashLoginBtn.jsx, moamoa/src/Components/Splash/SplashLogo.jsx, moamoa/src/Components/Splash/SplashStyle.js, moamoa/src/GlobalStyle.jsx, moamoa/src/Pages/Chat/ChatStyle.js, moamoa/src/Pages/Product/ProductList.jsx, moamoa/src/Recoil/ProductAtom.jsx
사용된 색의 명암이 대비되지 않아 접근성이 떨어져 변경했습니다.
색상 전역변수 지정은 유지보수성과 가독성을 높이기 위해 사용하였습니다.
축제&체험 리스트는 추후에 데스크톱 반응형 우측 배너에 사용될 리스트를 리코일에 저장하였습니다.
https://app.contrast-finder.org/?lang=ko 를 이용해 
명암비가 4.5 이상이 되는 색상으로 변경했습니다.
색상 전역변수 지정
사용 
| 수정 전 |수정 후 |
|--------|--------|
| 스플래쉬 전|스플래쉬 후|
| ![image](https://github.com/FRONTENDSCHOOL7/final-18-moamoa/assets/88381607/88134028-e40e-4675-9e29-b6d73153f5cb)| ![image](https://github.com/FRONTENDSCHOOL7/final-18-moamoa/assets/88381607/1f982a31-a85d-43fc-ad69-810a5e2ca503) | |![image](https://github.com/FRONTENDSCHOOL7/final-18-moamoa/assets/88381607/88134028-e40e-4675-9e29-b6d73153f5cb)| ![image](https://github.com/FRONTENDSCHOOL7/final-18-moamoa/assets/88381607/1f982a31-a85d-43fc-ad69-810a5e2ca503) |
| 채팅리스트 전 |채팅리스트 후 |
| …
=> [♻️ Refactor]접근성 향상,색상 전역변수 지정,축제&체험 리스트 리코일 배열에 저장

moamoa/package-lock.json
package-lock.json(develop 브랜치)에서 더이상 필요하지 않은 gh-pages 관련 코드를 발견하여 삭제합니다.
Issue Number
close: #352
=> [🛠️ Chore] package-lock.json에서 gh-pages 관련 코드 삭제

src/Pages/Home/Home.jsx, src/Pages/Home/HomeSearch.jsx, src/Pages/Home/HomeStyle.jsx, src/Pages/Post/PostDetail.jsx, src/Pages/Post/PostDetailStyle.jsx, src/Pages/Product/ProductDetail.jsx, src/Pages/Product/ProductStyle.js
통합 style 파일 작성을 위해 기존에 작성해 둔 style 관련 코드들을 분리했습니다.
1. Home 페이지에 적용된 스타일 코드들을 스타일을 HomeStyle.jsx 파일로 모았습니다.
2. PostDetail 페이지에 적용된 스타일 코드들을 PostDetailStyle.jsx 파일로 모았습니다.
3. ProductDetail 페이지에 적용된 스타일 코드들을 ProductStyle.jsx 파일로 모았습니다.
우선 페이지에 적용된 스타일만 모았는데, 각각의 컴포넌트에 적용되어 있는 스타일 코드들은 어떻게 분리하면 좋을지 의견 나누고싶습니다..! 컴포넌트에 적용된 코드들까지 합쳐서 하나의 파일로 만들어야할까요..? ㅠㅠ 
Issue Number
close: #336
=> [♻️ Refactor]  Home, 게시글 상세, 축제 및 체험 상세 CSS 분리

public/index.html, src/Components/Product/ProductContents.jsx
배포 후 지도 출력 오류가 발생했습니다.
1. 인증키를 재발급 받아 .env 파일의 환경변수 설정을 다시 진행했습니다.
2. html 파일에 누락 된 카카오 api script 코드를 추가했습니다.
Issue Number
close: #357
=> [ 🔧 Fix ] 지도 출력 오류 해결

src/Breakpoints.jsx, src/Components/Common/Container.jsx, src/Components/Post/PostContents.jsx, src/Components/Post/PostItem.jsx, src/Components/Post/PostList.jsx, src/GlobalStyle.jsx, src/Pages/Home/HomeStyle.jsx
home 페이지 태블릿 반응형 구현했습니다.
1. GlobalStyle html font-size 속성값을 태블릿에서는 70%로 설정했습니다.
2. Breakpoints.jsx 파일 생성
분기점을 변수화 하고싶어 파일 생성 후 적용을 시도해보았으나, 적용이 되지 않는 문제가 발생했습니다.
적용 방법을 더 찾아보도록하겠습니다.
3. flex 속성 사용으로 인한 정렬 어려움 발생
현재 위의 이미지처럼 양쪽 여백이 브라우저 창 중심으로는 맞지만, 왼쪽 영역에서 가운데 정렬은 되지 않는 문제가 있습니다. float 속성을 사용하는 방법으로 코드를 변경해야할지 고민중입니다. nav bar 위치가 맞지 않는 문제가 있습니다 ㅠㅠ 해결 요청드립니다. @AYFG 
html font size 조정 및 공통 컴포넌트 사용으로인해 ui가 깨지는 곳이 여러 곳 있습니다. 작업 하는대로 PR보내겠습니다.
Issue Number
=> refactor: home 페이지 반응형 구현
