FRONTENDSCHOOL7/final-18-moamoa

- moamoa/src/Components/Common/Container.jsx
- moamoa/src/Components/Common/Footer.jsx
- moamoa/src/GlobalStyle.jsx
- moamoa/src/Pages/Product/ProductList.jsx
바디의 배경색은 앞으로 모든 
feat: 상품 리스트의 스타일,상세페이지 이동 구현하였고 축제와 체험 구분 렌더링은 
아직 구현하지 못했습니다.
다른 기능 상세페이지 이동, 행시기간 price 를 string으로 다시 바꿔 
ex)행사기간: 23.10.10~23.10.15 로 구현했습니다.
상세페이지 넘어가는 부분과 상품리스트의 정상출력에 문제가 생기면 말씀 부탁드립니다!
Issue Number #22 
> [✨ Feature] 상품 리스트 구현 축제,체험 구분 렌더링 빼고 구현

- moamoa/src/API/Auth/JoinAPI.jsx
- moamoa/src/API/Product/ProductUploadAPI.jsx
- moamoa/src/Hooks/Sign/useJoin.jsx
- moamoa/src/Pages/Product/AddProduct.jsx
+ 판매자 계정으로 회원가입 => 개인 계정으로 회원가입 => 기존 가입한 판매자로 로그인 시 userTypeAtom(판매자가 아닌 개인으로 출력)이 지속되지 않는 문제 발생했습니다.
+ 상품 등록도 유사한 문제가 발생했습니다. (축제/체험)
+ 회원 가입 시 사용자가 선택한 회원 유형에 따라 사용자 명 앞에 구분 문자를 넣었습니다.   
+ 개인: [i]사용자 명
+ 기업 및 기관: [o]사용자 명
+ 상품 등록 시 사용자가 선택한 행사 유형에 따라 상품 명 앞에 구분 문자를 넣었습니다.
+ 축제: [f]상품 명
+ 체험: [e]상품 명
Issue Number
close: # 98
> [🔧 Fix] 회원가입 시 회원유형 선택 / 상품등록 시 행사유형 선택 기능 수정

- moamoa/src/Pages/Splash/Landing.jsx
- [] 🧹 불필요한 코드는 제거했나요?
콘솔로그의 오류가 스플래쉬 화면에서 계속 발견되었습니다.
동작은 이상이 없었습니다.
<LoginModal visible={modalActive}> -> 수정 전 
<LoginModal visible={modalActive ? true :false}> -> 수정 후
DOM에서 prop은 유효한 속성이 아니므로 경고를 주었습니다.
const LoginModal = styled.div` -> 수정 전 
const LoginModal = styled.div.withConfig({     -> 수정 후
shouldForwardProp: (prop) => prop !== 'visible',
})
visible prop의 값을 true와 false가 전달 되도록 수정하였고 , 
shouldForwardProp 함수는 컴포넌트로 전달된 prop 중에서 실제 DOM 엘리먼트에 전달할 것인지 여부를 결정하는 함수입니다. 이 함수를 통해 원하는 prop을 전달하고, 다른 prop을 필터링하여 DOM에 전달하지 않을 수 있습니다.
그러므로 DOM에 prop이 필터링 되기 때문에 <LoginModal visible={modalActive}> -> 수정 전 
<LoginModal visible={modalActive ? 'true' : 'false'}> -> 수정 후 는 수정 전으로 바꾸어도 오류는 나지 않습니다
styled-components는 컴포넌트에 전달된 모든 prop을 DOM 엘리먼트로 전달합니다 이 때 브라우저에서 인식하지 못하는 prop이 포함되면서 React에서 경고나 오류가 …
> [🔧fix]  Splash 화면에서 콘솔에 나오는 오류

- moamoa/src/Components/Common/PostCardUser.jsx
게시글 사용자 정보 클릭시 사용자 프로필로 이동하도록 기능 추가 했습니다!
▼▼▼▼  클릭시 이동  ▼▼▼▼
Issue Number
close: #113
> [✨ Feature] 사용자 프로필로 이동 기능 추가

- moamoa/src/API/Product/ProductDeleteAPI.jsx
- moamoa/src/Pages/Product/AskBtn.jsx
+ 상품(벽초지수목원 가을꽃 국화축제) 삭제 전후
--- | --- | 
+ 상품 삭제 버튼 클릭 시 상품이 삭제되고 상품 리스트로 이동하게 처리했습니다.
+ 하지만 사용자가 실수로 삭제 버튼을 클릭하는 경우의 수도 고려하여 추가 기능으로 삭제 확인 메세지를 넣어봐도 좋을 것 같습니다!
Issue Number
close: # 131
> [✨ Feature] 상품 삭제 기능 구현

- moamoa/src/Components/Common/Button.jsx
- moamoa/src/Components/Common/FollowUser.jsx
- moamoa/src/Components/Common/FollowingUser.jsx
- moamoa/src/Components/Common/Footer.jsx
- moamoa/src/Pages/Product/ProductList.jsx
기능에는 문제없지만 콘솔에 오류가 발견이 되어 해결했습니다.
스타일컴포넌트 사용 미숙으로 인한 오류였습니다.
푸터의 기능이 빠르게 동작하지 않고 간헐적으로 두 번 이상 클릭을 해야 이동하는 현상이 있었습니다.
팔로우 팔로잉 페이지 오류는 버튼 컴포넌트의 오류였습니다.
props가 DOM 요소로 렌더링이 되어 생기는 오류였고,
prop 이름 앞에 달러 기호를 붙여서 일시적인 prop으로 바꾸었습니다.
푸터 콘솔 오류는 DOM 요소로 boolean이 아닌 값이 넘어가서 생긴 오류였습니다. 
해결방안은  true와 false 앞에 + 기호를 붙여 콘솔 오류를 제거했습니다.
푸터 기능 오류는 이미지에 온클릭 이벤트가 붙어있어서 생겼습니다.
버튼으로 온클릭 이벤트를 옮겨주어 해결하였습니다.
이 오류는 다른 조의 이미지가 섞여 들어와서 생긴 오류로 생각됩니다.
참고링크:https://maximeblanc.fr/blog/how-to-fix-the-received-true-for-a-non-boolean-attribute-error/
https://gist.github.com/meddokss/009cdb5192e487654c0d90cd8f692214
https://styled-components.com/docs/api#transient-props
Issue Number #144 #145 #147 
> [🔧fix] 버튼 컴포넌트 콘솔 오류와 푸터 콘솔 오류 해결했습니다.

- moamoa/src/Assets/icons/icon-usertype-check.svg
- moamoa/src/Components/Common/ProfileDetail.jsx
- moamoa/src/Components/Common/ProfileDetailPost.jsx
- moamoa/src/Components/Common/ProfileDetailProduct.jsx
- moamoa/src/Components/Post/PostCardList.jsx
- moamoa/src/Pages/Home/Home.jsx
- moamoa/src/Pages/Post/UloadEditPostStyle.jsx
- moamoa/src/Pages/Profile/EditProfile.jsx
- PostCardList.jsx : 프로필 상세 페이지에서 어색하게 출력되어 padding-top을 수정하였습니다.
- Home.jsx : PostCardList의 padding값 조정으로 발생한 어색한 부분을 수정하였습니다.
- 프로필 수정, 게시글 등록, 게시글 수정 페이지에서 쓰이는 헤더의 높이와 border-bottom을 다른 헤더와 동일하게 수정했습니다.
프로필 상세 페이지
- 판매자 계정 인증 아이콘을 수정하였습니다.
- 사용자 프로필 이미지의 배경이 투명일 경우 화면 뒷배경이 비쳐 보이는 부분을 하얗게 바꾸었습니다.
- 판매자 계정에서 상품이 하나도 등록되지 않았을 경우 발생한 레이아웃 오류를 수정했습니다.
- 게시글 목록 부분에서 어색한 레이아웃을 수정하였습니다.
프로필 수정 페이지
- 사용자 프로필 이미지 또는 카메라 아이콘을 클릭할 시 파일 선택 창이 뜰 수 있도록 했습니다.
- input text에 focus가 가면 border-bottom의 색이 바뀌도록 했습니다.
- 사용자 프로필 이미지의 배경이 투명일 경우 화면 배경이 하얗게 되도록 설정했습니다.
| 프로필 상세 페이지 수정 | 프로필 수정 페이지 스타일 작업 |
| --- | --- |
| ![프로필 상세 스타일 수정](https://github.com/FRONTENDSCHOOL7/final-18-moamoa/assets/116999139/50ee75b7-444e-4082-8403-06f59883808d) | ![프로필 수정 …
> [🌈 Style] 프로필 수정 페이지 스타일 작업

- moamoa/src/API/Img/UploadImageAPI.jsx
- moamoa/src/Hooks/Sign/useJoin.jsx
- moamoa/src/Pages/Join/Join.jsx
+ 회원가입 시 사용자가 프로필 이미지를 등록하지 않으면 기본 프로필 이미지로 가입이 됩니다.   
하지만 로그인 후 프로필 페이지를 확인해보니 이미지가 뜨지 않는 현상이 발생하여 해결했습니다.
+ UploadImageAPI return 값을 수정하고 useJoin에서 이미지 초기값으로 기본 프로필 이미지를 등록했습니다.
--- | --- | 
Issue Number
close: # 165
> [🔧 Fix] 기본 프로필 이미지로 회원가입 시 프로필 이미지가 뜨지 않는 문제 수정

- moamoa/src/Hooks/Sign/useJoin.jsx
- moamoa/src/Pages/Join/Join.jsx
+ UI 요소를 일관되게 유지하기 위해 회원가입 시 계정명과 소개란에 글자 수 입력 조건을 설정했습니다.
-  [x] 회원가입(프로필 설정) 글자 수 입력 조건 추가
--- | --- | 
Issue Number
close: # 178
> [✨ Feature] 회원가입(프로필 설정) 글자 수 입력 조건 설정

- moamoa/src/Components/Common/ProductSharedStyle.jsx
- moamoa/src/Pages/Product/AddProduct.jsx
- moamoa/src/Pages/Product/EditProduct.jsx
+ 상품 등록 페이지와 상품 수정 페이지의 스타일 수정했습니다.
+ 상품 등록 페이지와 상품 수정 페이지의 상품 명(행사 명)의 글자 수를 제한 설정했습니다.
Issue Number
close: # 186
> [🔧 Fix] 상품 등록과 상품 수정 페이지 스타일 수정 및 상품 명 글자 수 제한 설정

- moamoa/src/Components/Common/HeaderKebab.jsx
- moamoa/src/Router/AppRoutes.js
- moamoa/src/Router/PrivateRoute.js
+ 사용자가 로그아웃 상태일 시 일부 페이지 접근을 제한합니다.
+ splash, 로그인, 회원가입, 404 페이지는 예외입니다.
+ **구현을 위하여 HeaderKebab.jsx와 AppRoutes.js 파일을 수정했습니다.**
Issue Number
close: # 197
> [✨ Feature] 사용자의 로그인 상태에 따른 경로 접근 제한

- moamoa/src/Components/Common/FormLoginAndJoin.jsx
- moamoa/src/Pages/Join/Join.jsx
- moamoa/src/Pages/Login/Login.jsx
+ 회원 가입 시 프로필 설정에서 사용자 명 글자 수 제한은 2~10자 이내입니다.
+ 폼 제출 할 때는 2자 이상 출력하라는 안내 문구와 함께 제출이 되지 않습니다.
+ 하지만 이전 단계인 버튼 활성화 단계에서 사용자 명이 1글자임에도 활성화되어 이를 수정했습니다.
+ 프로필 설정 페이지에서 버튼 활성화 조건 수정(사용자 명 글자 수 2자 이상)
+ 로그인, 회원 가입, 프로필 설정 페이지에서 화면 확대 시 비는 배경 채우기, 여백 주기 완료
Issue Number
close: # 199
> [🔧 Fix] 프로필 설정 시 사용자명 글자 수 입력조건 미충족임에도 버튼 활성화되는 문제 및 스타일 수정

- moamoa/src/Components/Common/ProfileDetailPost.jsx
- moamoa/src/Components/Common/ProfileDetailProduct.jsx
- moamoa/src/Pages/Follow/FollowerList.jsx
- moamoa/src/Pages/Follow/FollowingList.jsx
- moamoa/src/Pages/Home/HomeFeed.jsx
- moamoa/src/Pages/Product/ProductList.jsx
- moamoa/src/Pages/Profile/EditProfile.jsx
- moamoa/src/Pages/Profile/MyProfile.jsx
- moamoa/src/Pages/Profile/YourProfile.jsx
- position: fixed 추가로 발생한 레이아웃 이슈 해결 : 팔로잉 리스트, 팔로우 리스트, 축제목록 페이지
- homefeed 페이지에 흰색 배경 추가
- 프로필 수정 페이지에서 발생한 이슈 해결
- 프로필 수정 페이지에 계정 id와 소개글의 글자수 제한을 추가
- 프로필 상세 페이지 상품 리스트에서 축제일 경우 [e]가 노출되는 문제 해결
- 프로필 상세 페이지에서 조건부 렌더링을 사용하여 이미지가 없는 경우에는 li를 생성하지 않는 기능을 추가한 뒤 발생한 오류를 해결
프로필 수정 페이지
- 게정 id는 2 ~ 15자의 글자 수 제한을, 소개글은 2 ~ 50자의 글자수 제한을 추가했습니다.
- 판매자/개인 계정을 구분하기 위해 추가한 [o]/[i]가 프로필 수정 페이지에 그대로 노출되며 사용자가 직접 [o]/[i]를 입력하였을때 판매자/개인 계정으로 바뀌는 문제를 해결했습니다.
프로필 상세 페이지
- 상품 리스트에서 축제일 경우 [e]가 노출되는 문제를 해결했습니다.
-  조건부 렌더링을 사용하여 이미지가 없는 경우에는 li를 생성하지 않는 기능을 추가한 뒤에 발생한 벤토 버튼을 클릭하였을 때 목록형 게시글도 출력되는 문제를 해결했습니다.
계획
- 팔로우/언팔로우 버튼 기능 이슈 해결
Issue Number #181
> [✨ Feature / 🌈 Style / 🔧 Fix] 프로필 수정 페이지 닉네님 작성 오류 수정 및 글자수 제한 기능 추가 및 프로필 상세페이지 디자인 수정

- moamoa/src/API/Post/PostDetailAPI.jsx
- moamoa/src/Hooks/Sign/useLogin.jsx
+ 로그인 성공 후 홈 화면으로 이동, 뒤로 가기 클릭 시 로그인 화면으로 이동이 가능합니다.
+ 로그아웃 하지 않은 상황에서 로그인 화면으로 이동 가능이 가능합니다.
+ 위 상황 모두 로그인 했을 당시 local storage 값이 그대로 저장되어 있어 이를 초기화하는 작업 진행합니다.
+ 로그인 후 홈에서 뒤로 가기, 로그인 페이지로 이동 (왼쪽: 수정 전, 오른쪽: 수정 후)   
--- | --- | 
+ PostDetailAPI '}' expected 에러 수정합니다.
Issue Number
close: # 207
> [🔧 Fix] 다른 화면에서 로그인 화면으로 이동 시 local storage에 값이 남아있는 문제

- moamoa/src/Components/Comment/AddCommentBtn.jsx
- moamoa/src/Components/Common/ProfileDetailProduct.jsx
- moamoa/src/Components/Home/HomePostCardList.jsx
- moamoa/src/Components/Modal/ReportModal.jsx
- moamoa/src/Components/Post/PostCardItem.jsx
- moamoa/src/Components/Post/PostCardList.jsx
- moamoa/src/Components/Post/PostCardUser.jsx
- moamoa/src/Pages/Product/AskBtn.jsx
- moamoa/src/Pages/Product/ProductDetail.jsx
게시글 상단 유저 프로필 클릭 시 내 프로필의 경로가 myInfo가 아닌 계정명으로 이동하게 되는 문제가있었고 이 문제로 인해 내가 쓴 게시글의 더보기 버튼을 눌렀을때 신고하기 모달이 활성화 되는 문제가 추가로발생했습니다.
로그인한 accountname이 게시글 작성자의 accountname과 같을경우 myInfo 페이지로 이동하게 경로를 수정했습니다.
Issue Number
>  [ 🔧Fix ] 게시글 상단 유저 프로필 이동 경로 수정

- moamoa/src/Components/Common/HeaderChat.jsx
- moamoa/src/Pages/Search/Loader.jsx
- moamoa/src/Pages/Search/Search.jsx
검색한 내용을 지우면 렌더링 되었던 내용이 그대로 남아있었습니다.
cancel이라는 변수를 사용하여 비동기 작업이 중간에 취소되지 않도록 사용했습니다.
검색어가 변경될 떄 검색 결과를 setSearchResults(null) 로 초기화 했습니다.
빠르게 지웠을 때 계속 Loading이 되는 현상이 생겨 setTimeout을 사용해 로딩이 3초간 지속되면 검색 결과가 없다는 안내문구로 바뀌게 했습니다.
로딩이 되는 시간에 로딩 이미지를 추가하였습니다.
https://github.com/FRONTENDSCHOOL7/final-18-moamoa/assets/88381607/a9d96d82-65b2-48be-af12-bb5834faf06b
로딩 이미지의 디자인이 괜찮은지 봐주시면 좋겠습니다.
Issue Number #217 
> [🔧fix]검색 페이지 검색 내용을 지우면 안내문구, 로딩 이미지 추가

- moamoa/src/Components/Home/HomePostCardList.jsx
- moamoa/src/Components/Post/PostCardItem.jsx
- moamoa/src/Components/Post/PostCardList.jsx
- moamoa/src/Components/Post/PostCardUser.jsx
- moamoa/src/Pages/Product/ProductDetail.jsx
- moamoa/src/Pages/Search/Search.jsx
게시글 유저의 프로필 및 검색화면에서 기관 사용자의 공식 마크가 나오도록 수정했습니다.
Issue Number
close: #231
> [ 🔧 Fix ] 게시글 및 검색화면 공식 마크 출력

- moamoa/src/Hooks/Auth/useLogin.jsx
- moamoa/src/Pages/Auth/Login.jsx
+ 모아모아를 처음 방문한 사용자가 회원 가입 없이 사이트를 체험할 수 있도록 기능을 추가했습니다. 
+ 체험하기 클릭 시 자동 로그인 되어 홈으로 이동합니다.
+ 테스트 계정은 moa_festa 계정을 사용했습니다.
+ 기존의 사이트 사용자가 로그인할 때 이동 동선을 고려하여 비밀번호 입력 창 바로 아래에 로그인하기 그 다음에 체험하기를 두었습니다.
+ 기능 추가하면서 체험하기 버튼에 로그인 버튼과 동일한 스타일을 적용했는데 혹시 다른 좋은 아이디어 있으시다면 말씀 부탁 드리겠습니다:) 
Issue Number
close: # 279
> [✨ Feature] 테스트 계정으로 로그인 기능 추가

- moamoa/src/Components/Common/ProductSharedStyle.jsx
- moamoa/src/Pages/Product/ProductAdd.jsx
- moamoa/src/Pages/Product/ProductEdit.jsx
행사 상세 페이지의 카카오 지도에서 보다 정확한 위치 표시를 위해 행사 등록 시 행사 장소를 추가할 수 있도록 설정합니다.
1. 행사 장소 label과 input을 생성합니다.
2. useState를 사용하여 상태 location을 추가합니다.
3. 행사 등록(상품 등록) 시 product 객체의 link 속성 값에 ‘상세설명+행사장소' 형태로 서버에 데이터를 보냅니다.
Req |Res
--- | --- | 
행사 수정 페이지의 행사 장소는 상세 페이지 작업 끝나시면 추가하겠습니당:)
다음 작업은 이미지 최적화 또는 상품 등록 코드 리팩토링하겠습니다!
Issue Number
close: # 296
> [✨ Feature] 행사 등록(상품 등록) 시 행사 장소 추가

- moamoa/src/Hooks/Product/useDateValidation.jsx
- moamoa/src/Pages/Product/ProductAdd.jsx
- moamoa/src/Pages/Product/ProductEdit.jsx
불필요한 상태 변수를 줄이고 중복된 함수는 추출했습니다.
상품 등록 또는 수정 폼 제출 시 누락된 입력사항이 있다면 메세지가 출력되도록 합니다.
상품 수정 폼에서 행사 장소를 추가합니다.
상품 등록 또는 상품 수정 폼에서 제출 버튼(등록, 수정) 위치를 바꾸었습니다. 스타일 상으로는 헤더에 위치해있는 것이 맞지만 html 문서 구조를 생각했을 때 폼 안에 제출 버튼이 위치해야 한다고 생각했습니다. 스타일은 추후 수정하겠습니다! 
+ useDateValidation.jsx
+ startDate와 endDate에서 '-'를 제거하는 로직이 중복으로 사용되고 있어 함수로 추출했습니다.
+ 상태변수 progressPeriod는 업데이트하기 위해 특별한 작업을 수행할 필요가 없습니다. 따라서 불필요한 렌더링을 줄이기 위해 일반 변수로 변경했습니다.
상태 변수 startDate, endDate로 progressPeriod(진행기간)를 계산합니다.
+ 기능과 목적을 명확히 하도록 훅 이름 변경합니다. 
시작 날짜와 종료 날짜를 받아서 특정 형식으로 변환하고, 이 두 날짜의 유효성을 검사하므로 useProgressPeriodEffect => useDateValidation 변경
+ ProductAdd.jsx, ProductEdit.jsx
+ Feat: 사용자가 상품 등록 시 필수 입력사항을 누락했다면 메세지를 출력합니다. 
+ 필수 입력사항 누락 메세지 스타일은 스타일 수정 작업 때 진행하겠습니다!
+ ProductEdit.jsx
+ Feat: 상품(행사) 수정 페이지에 행사 장소 추가했습니다. (스크린 샷 첨부)
+ …
> [♻️ Refactor /✨ Feature] 상품 등록 및 수정 코드 리팩토링, 상품 수정 페이지 행사 장소 추가

- moamoa/src/Components/Product/ProductForm.jsx
- moamoa/src/Hooks/Auth/useSignUp.jsx
- moamoa/src/Hooks/Product/useProductData.jsx
- moamoa/src/Hooks/Product/useSubmitProductForm.jsx
- moamoa/src/Pages/Product/ProductAdd.jsx
- moamoa/src/Pages/Product/ProductEdit.jsx
- moamoa/src/Utils/handleUploadImage.jsx
+ 유지보수성을 높이기 위해 상품 등록과 수정 컴포넌트의 중복 로직을 분리했습니다.
+ 함수가 하나의 역할만 하도록 이미지 업로드 함수를 수정합니다.
+ 행사 등록, 행사 수정 시 product 객체의 link 속성 값에 ‘상세설명+[l]행사장소' 형태로 서버에 데이터를 보내도록 수정합니다.
1. 상품등록과 상품수정 컴포넌트 간에 중복 로직 분리
- 공통 컴포넌트: ProductForm.jsx
- 커스텀 훅: useProductData.jsx, useSubmitProductForm.jsx
- useProductData 훅은 상품 데이터를 관리하고 useSubmitProductForm훅은 폼 제출을 처리합니다.
2. 이미지 업로드 함수 수정(handleUploadImage.jsx)
- setter 함수를 제거하고 이미지 업로드 API 응답만 받아오도록 합니다.
- 회원가입 시 프로필 설정, 상품 등록, 상품 수정에서 해당 함수를 사용했습니다.
3. 행사 등록, 행사 수정에서 link 속성값 변경
- ‘상세설명+행사장소' => ‘상세설명+[l]행사장소'
- 구분자 [l]은 location의 'l'입니다.
Issue Number
close: # 301
> [♻️ Refactor] 상품 등록과 상품 수정 컴포넌트 간에 중복 로직 분리

- moamoa/src/Components/Modal/DeleteModal.jsx
- moamoa/src/Components/Modal/FooterModal.jsx
- moamoa/src/Components/Post/PostList.jsx
- moamoa/src/Components/Post/PostMoreBtn.jsx
- moamoa/src/Components/Product/ProductContents.jsx
- moamoa/src/Pages/Product/ProductAdd.jsx
행사명으로 검색한 위치를 지도에 표기해 상세 주소가 명시되지 않는 문제가 있어 이를 수정했습니다.
상품 등록시 추가해준 행사 장소 데이터를 '+[l]' 구분자를 통해 잘라냈고, 이를 사용해 지도가 표시되도록 했습니다.
주소-좌표간 변환을 통해 지도를 표시하면 아래와 같이 정확한 위치에 마커가 찍히지 않습니다. 
키워드 검색으로 진행할 경우 너무 많은 마커가 생성됩니다..
위의 두가지의 방법 중 어떻게 지도가 출력되게 하는게 좋을까요...? ㅠㅠ
1. 조금 어긋나더라도 하나의 마커만 출력
2. 키워드에 해당하는 모든 마커가 출력
의견 부탁드리겠습니다!
Issue Number
close: #303
> [♻️ Refactor] 상품 상세 페이지 행사 장소 추가

- moamoa/src/Components/Common/ProductFormStyle.jsx
팀원 분들의 코멘트를 통해 새로운 대안이 떠올라서 아래와 같이 작업했습니다!
저장버튼이 하단에 고정되도록 수정합니다!   
사용자 경험, 컴포넌트 재사용성, 시맨틱한 마크업, 키보드 탭 순서 
4마리 토끼를 다 잡을 수 있는 방법이라 생각했습니다:)
행사 등록 |행사 수정
--- | --- | 
버튼 크기가 적당한지 궁금합니다! 
하단 내비게이션과 똑같이 높이를 맞춘 상황입니당
Issue Number
close: # 310
> [🔧 Fix] 상품(행사)저장 버튼 위치 조정

- moamoa/src/Components/Common/ChatMoreBtn.jsx
- moamoa/src/Components/Common/ChatPhoto.jsx
- moamoa/src/Components/Common/Container.jsx
- moamoa/src/Components/Common/FollowingUser.jsx
- moamoa/src/Components/Splash/LoginModal.jsx
- moamoa/src/Components/Splash/SplashLoginBtn.jsx
- moamoa/src/Pages/Chat/ChatRoomAccount.jsx
- moamoa/src/Pages/Chat/ChatRoomDarkHorse.jsx
- moamoa/src/Pages/Chat/ChatRoomKim.jsx
- moamoa/src/Pages/Chat/ChatRoomSumiDad.jsx
- moamoa/src/Pages/Product/ProductList.jsx
축제&체험 리스트 페이지를 축소했을때 푸터가 컨테이너 배경색과 이어지지 않는 문제점이 있었습니다.
로그인한 유저에게 moamoa 로고를 보여주는 시간이 짧았습니다.
채팅방 이미지의 alt가 들어있지 않았습니다.
축제&체험 리스트 페이지는 ProductListWrap에 배경색을 넣고
Container는 100vh로 수정했습니다.
스플래쉬 로고 시간 수정은 setTimeOut의 시간을 1초 늘렸습니다.
축제&체험 리스트 수정 전
축제&체험 리스트 수정 후
채팅방 수정 전
채팅방 수정 후
Issue Number #319 #318 #295 
> [🔧 Fix/ 🌈 Style]축제&체험 리스트 페이지 스타일 수정, 스플래쉬 로고 시간 수정,이미지 alt 삽입

- moamoa/src/Components/Product/ProductOutput.jsx
- moamoa/src/Components/Product/filterActive.js
- moamoa/src/Components/Product/formatEventDate.js
productOutput.jsx의 코드에서 재사용 할 수 있는 코드를 분리했습니다.
행사명과 행사기간의 태그가 p태그로 있었습니다.
filterActive 부분을 떼어서 .js 파일로 분리했습니다.
행사기간 부분도 재사용성을 높이기 위해 .js 파일로 분리하였고,
사용자에게 시각적으로 보이는 부분의 시작기간 ~ 끝기간 함수와
시맨틱 태그를 위한 함수 2개를 생성하였습니다.
dateTime에 날짜를 하나씩 담기위해 태그를 두 개로 변경했습니다.
(formatEventStartDate,formatEventEndDate = 시각적으로 보이는 함수)
(semanticStartDate,semanticEndDate = 시맨틱 태그를 위해 dateTime에 넣을 함수)
productOutput.jsx 컴포넌트 분리 후 return 부분의 
이 부분을 깔끔하게 만들 방법을 찾지 못했습니다.
Issue Number #317 
> [♻️ Refactor]행사&축제 페이지 코드 컴포넌트 분리와 행사 기간 시맨틱 태그 변경

- moamoa/src/Components/Common/ProductImgBox.jsx
- moamoa/src/Components/Product/ProductOutput.jsx
프로필의 진행중인 행사에서 이미지 컴포넌트를 같이 사용하여 ProductImgBox를 확장하여 ProductListImgBox 컴포넌트를 사용하여 축제&체험 리스트의 이미지 크기를 조정하고 한 줄로 바꾸었습니다.
2열
1열
날짜를 우측으로 둘 경우 "아침고요수목원 오색별빛정원전"과 같은 축제의 이름이 길면 날짜와 겹쳐서 보기 좋지않아 
이름과 날짜는 원래 형식으로 사용했습니다.
피드백 주시면 수정하겠습니다!!
Issue Number
> [🌈 Style]상품&축제 리스트의 열을 1 줄로 변경

- moamoa/src/Components/Common/HeaderComponents.jsx
- moamoa/src/Components/Search/NotFound.jsx
- moamoa/src/Pages/Search/Search.jsx
…cus border color 수정
뒤로가기 버튼이 다른 페이지와 다른 위치에 있었습니다.
인풋 크기가 작은 의견과 검색 실패 이미지의 위치가 애매한 의견이 있었습니다.
검색 실패 이미지의 위치를 중앙 배치 했습니다.
인풋의 크기를 늘렸습니다.
뒤로가기 버튼의 위치를 다른 페이지와 맞추었습니다.
수정 전 
수정 후
Issue Number #327 
> [🌈 Style]검색 실패 이미지 중앙 배치, 뒤로가기 버튼 밀림 수정, 유저 검색 iuput 크기 수정, input 포커스 보더색 변경

- moamoa/src/Components/Common/ProductFormStyle.jsx
- moamoa/src/Components/Modal/RequiredInputModal.jsx
- moamoa/src/Components/Product/ProductForm.jsx
- moamoa/src/Hooks/Product/useProductData.jsx
- moamoa/src/Pages/Product/ProductAdd.jsx
- moamoa/src/Pages/Product/ProductEdit.jsx
1. 기존에는 사용자가 폼 제출 시 필수 정보를 미입력한다면 확인 요청을 보낼 때 저장 버튼 위에 메세지가 출력 되도록 했습니다. 하지만 스크롤 상 화면에 메세지가 안 보이는 경우가 있다는 것을 인지하게 되었고 이에 알림 모달로 방식을 수정했습니다.
2. 상품 등록과 상품 수정 컴포넌트 간의 공통 로직을 추출하여 공통 컴포넌트로 사용 중이던 ProductForm 파일에 추가했습니다. (ex. 저장 버튼 클릭 시 처리 과정 등) 
Issue Number #334
> [🔧 Fix / ♻️ Refactor] 상품 등록, 상품 수정 폼 미입력 정보 확인 요청 방식 수정 / 공통 로직 추출

- moamoa/src/Components/Product/ProductForm.jsx
- moamoa/src/Hooks/Auth/useSignUp.jsx
- moamoa/src/Hooks/Common/useImage.jsx
- moamoa/src/Hooks/Product/useProductData.jsx
- moamoa/src/Pages/Auth/SignUp.jsx
- moamoa/src/Pages/Post/EditPost.jsx
- moamoa/src/Pages/Post/UploadPost.jsx
- moamoa/src/Pages/Product/ProductAdd.jsx
- moamoa/src/Pages/Product/ProductEdit.jsx
- moamoa/src/Pages/Profile/EditProfile.jsx
이미지 크롭을 위해 사용되고 있는 아래 함수들이 각 컴포넌트(프로필 설정 & 수정, 상품 등록 & 수정, 게시글 등록 & 수정)에서 재사용되고 있습니다. 
1. onSelectFile
2. onCancel
3. setCroppedImageFor
별도의 훅 파일로 분리하여 컴포넌트의 복잡성을 줄였습니다.
Issue Number #344
> [♻️ Refactor] 재사용되는 이미지 크롭 함수들 훅으로 분리

- moamoa/src/Components/Common/Header/HeaderComponents.jsx
유저 검색 페이지로 이동했을 때 포커스가 인풋창으로 되어있지 않아 사용자 경험이 좋지 않을 것으로 판단했습니다.
Components/Common/Header/HeaderComponents.jsx의 HeaderSearch 컴포넌트에
useRef를 이용하여 구현했습니다.
설정 전
설정 후 
Issue Number #346 
close: # #346
> [♻️ Refactor]유저 검색 페이지 렌더링 시 포커스

- moamoa/src/API/Product/ProductAPI.jsx
- moamoa/src/Components/Product/ProductOutput.jsx
- moamoa/src/Components/Product/filterActive.js
- moamoa/src/Components/Product/formatEventDate.js
축제&체험의 수가 많아지면 초기 렌더링이 늦어질 것으로 생각되었습니다.
축제&체험의 기한이 지났지만 데이터가 남아있었습니다.
렌더링
[nextPage,setNextPage] useState 에 초기값 4를 넣고 스크롤이 바닥에 닿으면
setNextPage에 이전 값 + 4를 넣었습니다.
기한 지난 축제&체험
오늘의 날짜를 담은 todayDate와 축제 기한의 마지막 날인 expEndDate를 비교하여 지났다면 filteredProducts 변수에 담기지 않게 하였습니다.
기한 지난 축제 & 체험 수정 전
기한 지난 축제 & 체험 수정 후
기한이 지난 축제&체험을 볼 수 있는 공간이 필요한지 의견 주시면 감사하겠습니다.
Issue Number
>  [♻️ Refactor]축제&체험 4개씩 렌더링,기한이 지난 축제&체험 필터링

- src/Components/Common/Header/HeaderKebab.jsx
로그아웃 후 다른 계정으로 로그인 했을 때 이전 사용자가 팔로잉 하고 있는 유저의 게시글이 홈 피드에 나타나는 오류가 있었습니다.
로그아웃 시 로컬 스토리지에 저장된 토큰만 지우는 것이 아니라 recoil-persist도 초기화 해 문제를 해결했습니다.
home 화면에서 처음에 검색하기 화면이 나오는 문제가 있어, 해결하도록 하겠습니다.
close: #282
> [ 🔧 Fix ] 로그인 시 이전 사용자 데이터가 남는 오류
